version: '2.4'
services:

  frontend:
    image: taxd/docker-frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m

  nginx:
    restart: always
    image: taxd/docker-nginx
    ports:
      - '80:80'
    mem_limit: 128m
    links:
      - frontend
      - backend

  backend:
    image: taxd/docker-backend
    container_name: app_backend
    mem_limit: 128m
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      MYSQL_HOST: docker-fullstack-mysql.cadsjl2lglqg.ap-northeast-2.rds.amazonaws.com
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 20191201
      MYSQL_DATABASE: taxd
      MYSQL_PORT: 3306

  # mysql:
  #   build: ./mysql
  #   restart: unless-stopped
  #   container_name: app_mysql
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - ./mysql/mysql_data:/var/lib/mysql
  #     - ./mysql/sqls/:/docker-entrypoint-initdb.d/
  #   environment:
  #     MYSQL_DATABASE:
  #     MYSQL_USER:
  #     MYSQL_ROOT_PASSWORD: